namespace com.jds.PathEditor.classes.client
{
    public enum IntFiles
    {       
        [Lineage2Ver(111)]
        ALAudio,
        [Lineage2Ver(111)]
        bighead,
        [Lineage2Ver(111)]
        cloak,
        [Lineage2Ver(111)]
        core,
        [Lineage2Ver(111)]
        d3ddrv,
        [Lineage2Ver(111)]
        engine,
        [Lineage2Ver(111)]
        Env,
        [Lineage2Ver(111)]
        hair,
        [Lineage2Ver(111)]
        ipdrv,
        [Lineage2Ver(111)]
        l2,
        [Lineage2Ver(111)]
        lineagemonster,
        [Lineage2Ver(111)]
        lineagemonster2,
        [Lineage2Ver(111)]
        lineagemonster3,
        [Lineage2Ver(111)]
        lineagemonster4,
        [Lineage2Ver(111)]
        lineagemonster5,
        [Lineage2Ver(111)]
        lineagemonster6,
        [Lineage2Ver(111)]
        lineagenpc,
        [Lineage2Ver(111)]
        lineagenpc2,
        [Lineage2Ver(111)]
        lineagenpcev,
        [Lineage2Ver(111)]
        LineageWarrior,
        [Lineage2Ver(111)]
        soulshot,
        [Lineage2Ver(111)]
        TimeEnv0,
        [Lineage2Ver(111)]
        TimeEnv1,
        [Lineage2Ver(111)]
        TimeEnv2,
        [Lineage2Ver(111)]
        TimeEnv3,
        [Lineage2Ver(111)]
        window,
        [Lineage2Ver(111)]
        windrv,
    }
}